source "https://rubygems.org"

gem "rails", ">= 8.1.2"
gem "nokogiri", "~> 1.16"
gem "puma", "~> 6.0"

gem "local_gem", path: "../local_gem"
gem "git_gem", git: "https://github.com/example/git_gem.git"

group :development, :test do
  gem "debug"
end
